Repository ckotzbauer/sbom-operator, pull requests merged in 2022-08, with the labels that each got.

#151 Add Pod-Informer
  README.md
  go.mod
  go.sum
  internal/daemon/daemon.go
  internal/job/job.go
  internal/kubernetes/kubernetes.go
  internal/processor/processor.go
  internal/syft/syft.go
  internal/syft/syft_test.go
  internal/target/dtrack/dtrack_target.go
  internal/target/git/git_target.go
  internal/target/oci/oci_target.go
  internal/target/oci/oci_target_test.go
  internal/target/target.go
  main.go
Labels: kind/feature, size/XXL, work-in-progress, target/git, target/dtrack, target/oci

#162 fix: Grant `watch` permissions on `Pods` to ServiceAccount
  deploy/standard/rbac.yaml
Labels: size/XS

#157 feat: add pod namespace as tag in dtrack project
  internal/processor/processor.go
  internal/target/dtrack/dtrack_target.go
  internal/target/git/git_target.go
  internal/target/oci/oci_target.go
  internal/target/oci/oci_target_test.go
  internal/target/target.go
Labels: kind/feature, size/S
