Repository ckotzbauer/sbom-operator, pull requests merged in 2022-01, with the labels that each got.

#7 chore: change the way of install syft
  Dockerfile
Labels: size/S

#9 chore: use syft version 0.36.0 on top layer
  Dockerfile
Labels: size/XS

#12 security: update opencontainers/image-spec
  go.mod
  go.sum
Labels: size/XS, kind/security

#13 feat: use syft module instead of binary
  Dockerfile
  go.mod
  go.sum
  internal/syft/syft.go
Labels: size/L
